/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module hardcodeROM_6 (
    input clk,
    input rst,
    input [4:0] address,
    output reg [53:0] value
  );
  
  
  
  localparam TEST_CASE = 1242'h37000f000a0000dc0028003c00075000500040000d40010001400073000400050000cc00140014000638857ac08ff888da15eb02001a216857ac08006881a15eb0215c01a6857ac08685759a15eb023117de6857ac08ec5f61a15eb020a0002ffffffff000107ffec0023ffcc10b0404b10653060001fffc000417fff8000ffff0200020000000007fff00018000000004000000040fffffffffffe;
  
  always @* begin
    value = TEST_CASE[(address)*54+53-:54];
  end
endmodule
