set projDir "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/vivado"
set projName "WhackAMikeTwoPlayRev2"
set topName top
set device xc7a35tftg256-1
if {[file exists "$projDir/$projName"]} { file delete -force "$projDir/$projName" }
create_project $projName "$projDir/$projName" -part $device
set_property design_mode RTL [get_filesets sources_1]
set verilogSources [list "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/au_top_0.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/reset_conditioner_1.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/beta_2.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/edge_detector_3.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/button_conditioner_4.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/alu_5.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/control_6.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/regfile_7.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/counter_8.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/random_9.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/random_dynamike_10.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/multi_seven_seg_p1_11.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/multi_seven_seg_p2_12.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/multi_seven_seg_win_13.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/pipeline_14.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/adder_15.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/boolean_16.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/shifter_17.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/compare_18.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/edge_detector_19.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/counter_20.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/counter_21.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/pn_gen_22.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/counter_23.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/counter_24.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/seven_seg_25.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/decoder_26.v" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/verilog/seven_seg_win_27.v" ]
import_files -fileset [get_filesets sources_1] -force -norecurse $verilogSources
set xdcSources [list "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/constraint/properties.xdc" "C:/Users/Advaitaa/Desktop/TERM4/Comp\ Struct/1D/WhackAMikeTwoPlayRev2/work/constraint/external.xdc" ]
read_xdc $xdcSources
set_property STEPS.WRITE_BITSTREAM.ARGS.BIN_FILE true [get_runs impl_1]
update_compile_order -fileset sources_1
launch_runs -runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
